<#
.SYNOPSIS
  Locks the dedicated Postgres instance to loopback-only, regardless of what the EDB
  installer's own defaults did. The instance's superuser password is a plaintext
  installer constant committed to this repo, so the actual safeguard has to be that the
  instance is never reachable off-box in the first place -- a public password only
  matters if the port is reachable.
#>
param(
    [Parameter(Mandatory = $true)][string]$DataDir,
    [Parameter(Mandatory = $true)][string]$PsqlPath,
    [string]$ServiceName = "mil-home-postgresql",
    [int]$Port = 5433,
    [string]$SuperUser = "postgres",
    [Parameter(Mandatory = $true)][string]$SuperPassword,
    [int]$TimeoutSeconds = 15
)

$ErrorActionPreference = "Stop"
$waitScript = Join-Path $PSScriptRoot "Wait-PostgresReady.ps1"

$confPath = Join-Path $DataDir "postgresql.conf"
$hbaPath = Join-Path $DataDir "pg_hba.conf"

# listen_addresses: force to loopback-only, whatever the installer's default was.
$conf = Get-Content $confPath
$listenLine = "listen_addresses = 'localhost'"
if ($conf -match "^\s*#?\s*listen_addresses\s*=") {
    $conf = $conf -replace "^\s*#?\s*listen_addresses\s*=.*$", $listenLine
}
else {
    $conf += $listenLine
}
Set-Content -Path $confPath -Value $conf -Encoding ascii

# pg_hba.conf: replace entirely so no wider rule from the installer's defaults survives.
$hbaContent = @"
# Generated by MIL-HOME installer (Secure-PostgresNetwork.ps1) -- loopback only.
# TYPE  DATABASE        USER            ADDRESS                 METHOD
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             ::1/128                 scram-sha-256
"@
Set-Content -Path $hbaPath -Value $hbaContent -Encoding ascii

Write-Host "Restarting $ServiceName to apply loopback-only network config..."
Restart-Service -Name $ServiceName -Force

& $waitScript -PsqlPath $PsqlPath -Port $Port -SuperUser $SuperUser -SuperPassword $SuperPassword -TimeoutSeconds $TimeoutSeconds
exit $LASTEXITCODE
